version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    rebase-strategy: auto
    commit-message:
      prefix: deps
      include: scope
    labels:
      - maven
    groups:
      maven-minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    rebase-strategy: auto
    commit-message:
      prefix: ci(deps)
      include: scope
    labels:
      - github-actions
    groups:
      github-actions-minor-patch:
        update-types:
          - minor
          - patch

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    rebase-strategy: auto
    commit-message:
      prefix: docker(deps)
      include: scope
    labels:
      - docker
    groups:
      docker-minor-patch:
        update-types:
          - minor
          - patch
