package com.chatapp.client;

import com.chatapp.model.dto.AuthDTOs.AuthFailedResponse;
import com.chatapp.model.dto.AuthDTOs.LoginSuccessResponse;
import com.chatapp.model.dto.ChatDTOs.*;
import com.chatapp.model.dto.GroupDTOs.*;
import com.chatapp.model.dto.NotificationDTO.NotificationEvent;
import com.chatapp.socket.protocol.Envelope;
import com.chatapp.socket.protocol.MessageCodec;
import com.chatapp.socket.protocol.MessageType;
import javafx.application.Application;
import javafx.application.Platform;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.collections.transformation.FilteredList;
import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.Parent;
import javafx.scene.Scene;
import javafx.scene.control.*;
import javafx.scene.layout.*;
import javafx.stage.Stage;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.ScheduledFuture;
import java.util.concurrent.TimeUnit;
import java.util.function.Consumer;

/** Professional JavaFX desktop client for the real-time chat application. */
public final class ChatClientApp extends Application {
    private final ChatClientConnection connection=new ChatClientConnection(this::onEnvelope,this::setConnectionState);
    private final MessageCodec codec=new MessageCodec(); private final ObservableList<UserSummary> users=FXCollections.observableArrayList(); private final ObservableList<GroupSummary> groups=FXCollections.observableArrayList(); private final ListView<String> messages=new ListView<>();
    private final Map<Long,Integer> renderedMessageRows=new HashMap<>(); private final Map<Integer,Integer> unreadUsers=new HashMap<>(); private final Map<Integer,Integer> unreadGroups=new HashMap<>();
    private final ScheduledExecutorService typingScheduler=Executors.newSingleThreadScheduledExecutor(r->{Thread t=new Thread(r,"chat-client-typing");t.setDaemon(true);return t;});
    private UserSummary selectedUser; private GroupSummary selectedGroup; private LoginSuccessResponse session; private Label conversationTitle,typingLabel,connectionStatus; private TextField composer; private ListView<UserSummary> peopleView; private ListView<GroupSummary> groupView; private ScheduledFuture<?> typingStopTask; private boolean typingActive;
    private final String host=System.getProperty("chatapp.server.host","localhost"); private final int port=Integer.getInteger("chatapp.server.port",5050);

    @Override public void start(Stage stage){stage.setTitle("Real-Time Chat");stage.setMinWidth(960);stage.setMinHeight(640);stage.setScene(styledScene(loginView(stage),980,680));stage.show();}
    private Scene styledScene(Parent root,double width,double height){Scene scene=new Scene(root,width,height);var css=getClass().getResource("/chat.css");if(css!=null)scene.getStylesheets().add(css.toExternalForm());return scene;}
    private Parent loginView(Stage stage){TabPane tabs=new TabPane();tabs.setTabClosingPolicy(TabPane.TabClosingPolicy.UNAVAILABLE);tabs.getTabs().add(new Tab("Sign in",loginForm(stage)));tabs.getTabs().add(new Tab("Create account",registerForm()));Label title=new Label("Real-Time Chat");title.getStyleClass().add("brand-title");Label subtitle=new Label("Fast, secure messaging for desktop");subtitle.getStyleClass().add("brand-subtitle");Label server=new Label("Server  •  "+host+":"+port);server.getStyleClass().add("muted");VBox root=new VBox(18,new VBox(4,title,subtitle),tabs,server);root.setAlignment(Pos.CENTER);root.setPadding(new Insets(50,120,50,120));root.getStyleClass().add("auth-shell");return root;}
    private VBox loginForm(Stage stage){TextField identity=new TextField();identity.setPromptText("Username or email");PasswordField password=new PasswordField();password.setPromptText("Password");Button submit=primary("Sign in");Label feedback=new Label();feedback.getStyleClass().add("error");Runnable action=()->{if(identity.getText().isBlank()||password.getText().isBlank()){feedback.setText("Enter both fields.");return;}submit.setDisable(true);feedback.setText("Connecting…");runAsync(()->{ensureConnected();return connection.login(identity.getText().trim(),password.getText()).join();},result->{session=result;stage.setScene(styledScene(dashboard(stage),1180,760));requestData();},error->{feedback.setText(errorText(error));submit.setDisable(false);});};submit.setOnAction(e->action.run());password.setOnAction(e->action.run());return card(identity,password,submit,feedback);}
    private VBox registerForm(){TextField username=new TextField();username.setPromptText("Username");TextField email=new TextField();email.setPromptText("Email");PasswordField password=new PasswordField();password.setPromptText("Password");PasswordField confirm=new PasswordField();confirm.setPromptText("Confirm password");Button submit=primary("Create account");Label feedback=new Label();feedback.getStyleClass().add("error");submit.setOnAction(e->{if(username.getText().isBlank()||email.getText().isBlank()||password.getText().isBlank()||confirm.getText().isBlank()){feedback.setText("Complete every field.");return;}submit.setDisable(true);feedback.setText("Creating account…");runAsync(()->{ensureConnected();return connection.register(username.getText().trim(),email.getText().trim(),password.getText(),confirm.getText()).join();},result->{feedback.getStyleClass().remove("error");feedback.setText("Account created. You can now sign in.");submit.setDisable(false);},error->{feedback.setText(errorText(error));submit.setDisable(false);});});return card(username,email,password,confirm,submit,feedback);}
    private VBox card(Control... controls){VBox box=new VBox(12,controls);box.setMaxWidth(520);box.setPadding(new Insets(24));box.getStyleClass().add("auth-card");return box;}
    private BorderPane dashboard(Stage stage){BorderPane root=new BorderPane();root.getStyleClass().add("dashboard");root.setTop(topBar(stage));root.setLeft(sidebar());root.setCenter(chatPane());return root;}
    private HBox topBar(Stage stage){Label title=new Label("Real-Time Chat");title.getStyleClass().add("top-title");Label account=new Label(session.getUsername());account.getStyleClass().add("account");Region spacer=new Region();HBox.setHgrow(spacer,Priority.ALWAYS);connectionStatus=new Label("● Connected");connectionStatus.getStyleClass().add("connected");Button logout=new Button("Sign out");logout.setOnAction(e->{stopTyping();try{if(connection.isConnected())connection.send(MessageType.C2S_LOGOUT,null);}catch(IOException ignored){}finally{connection.close();}session=null;selectedUser=null;selectedGroup=null;unreadUsers.clear();unreadGroups.clear();stage.setScene(styledScene(loginView(stage),980,680));});HBox bar=new HBox(14,title,spacer,connectionStatus,account,logout);bar.setAlignment(Pos.CENTER_LEFT);bar.setPadding(new Insets(14,18,14,18));bar.getStyleClass().add("top-bar");return bar;}

    private VBox sidebar(){TextField search=new TextField();search.setPromptText("Search people…");search.getStyleClass().add("sidebar-search");FilteredList<UserSummary> filteredUsers=new FilteredList<>(users,u->true);search.textProperty().addListener((obs,oldValue,value)->{String q=value==null?"":value.trim().toLowerCase();filteredUsers.setPredicate(u->q.isEmpty()||(u.getUsername()!=null&&u.getUsername().toLowerCase().contains(q)));});
        peopleView=new ListView<>(filteredUsers);peopleView.setPlaceholder(new Label("No matching users"));peopleView.setCellFactory(v->new ListCell<>(){protected void updateItem(UserSummary u,boolean empty){super.updateItem(u,empty);if(empty||u==null){setText(null);setGraphic(null);return;}Label dot=new Label("●");dot.getStyleClass().add("presence-dot");Label name=new Label(u.getUsername());name.getStyleClass().add("contact-name");Label status=new Label(u.getStatus()==null?"offline":u.getStatus());status.getStyleClass().add("contact-status");VBox text=new VBox(1,name,status);HBox row=new HBox(8,dot,text);Integer count=unreadUsers.get(u.getUserId());if(count!=null&&count>0){Label badge=new Label(count>99?"99+":String.valueOf(count));badge.getStyleClass().add("unread-badge");Region spacer=new Region();HBox.setHgrow(spacer,Priority.ALWAYS);row.getChildren().addAll(spacer,badge);}row.setAlignment(Pos.CENTER_LEFT);setGraphic(row);setText(null);}});peopleView.setOnMouseClicked(e->{UserSummary u=peopleView.getSelectionModel().getSelectedItem();if(u!=null)openUser(u);});
        groupView=new ListView<>(groups);groupView.setPlaceholder(new Label("No groups yet"));groupView.setCellFactory(v->new ListCell<>(){protected void updateItem(GroupSummary g,boolean empty){super.updateItem(g,empty);if(empty||g==null){setText(null);setGraphic(null);return;}Label name=new Label("# "+g.getName());name.getStyleClass().add("contact-name");Label members=new Label(g.getMemberCount()+" members");members.getStyleClass().add("contact-status");VBox text=new VBox(1,name,members);HBox row=new HBox(8,text);Integer count=unreadGroups.get(g.getGroupId());if(count!=null&&count>0){Label badge=new Label(count>99?"99+":String.valueOf(count));badge.getStyleClass().add("unread-badge");Region spacer=new Region();HBox.setHgrow(spacer,Priority.ALWAYS);row.getChildren().addAll(spacer,badge);}row.setAlignment(Pos.CENTER_LEFT);setGraphic(row);setText(null);}});groupView.setOnMouseClicked(e->{GroupSummary g=groupView.getSelectionModel().getSelectedItem();if(g!=null)openGroup(g);});
        Button create=new Button("＋  New group");create.setMaxWidth(Double.MAX_VALUE);create.setOnAction(e->createGroup());Button join=new Button("↗  Join by ID");join.setMaxWidth(Double.MAX_VALUE);join.setOnAction(e->joinGroup());VBox box=new VBox(8,section("PEOPLE"),search,peopleView,section("GROUPS"),groupView,create,join);VBox.setVgrow(peopleView,Priority.ALWAYS);VBox.setVgrow(groupView,Priority.ALWAYS);box.setPrefWidth(285);box.setPadding(new Insets(14));box.getStyleClass().add("sidebar");return box;}

    private VBox chatPane(){conversationTitle=new Label("Select a conversation");conversationTitle.getStyleClass().add("chat-title");typingLabel=new Label();typingLabel.getStyleClass().add("typing");typingLabel.setManaged(false);typingLabel.setVisible(false);Label hint=new Label("End-to-end protocol · messages persisted securely");hint.getStyleClass().add("muted");Button searchButton=new Button("⌕ Search messages");searchButton.setOnAction(e->searchPrivateMessages());HBox titleRow=new HBox(10,conversationTitle,new Region(),searchButton);HBox.setHgrow(titleRow.getChildren().get(1),Priority.ALWAYS);VBox header=new VBox(6,titleRow,typingLabel,hint);header.setPadding(new Insets(18));messages.setCellFactory(v->new ListCell<>(){protected void updateItem(String text,boolean empty){super.updateItem(text,empty);setText(empty?null:text);getStyleClass().removeAll("message-row","message-own","message-system");if(!empty&&text!=null){getStyleClass().add("message-row");if(text.startsWith("You:"))getStyleClass().add("message-own");else if(text.startsWith("System:"))getStyleClass().add("message-system");}}});composer=new TextField();composer.setPromptText("Write a message…");composer.textProperty().addListener((obs,oldValue,newValue)->handleTypingInput(newValue));Button send=primary("Send  ›");send.setOnAction(e->sendMessage());composer.setOnAction(e->send.fire());HBox input=new HBox(10,composer,send);HBox.setHgrow(composer,Priority.ALWAYS);input.setPadding(new Insets(14));VBox pane=new VBox(header,messages,input);VBox.setVgrow(messages,Priority.ALWAYS);pane.getStyleClass().add("chat-pane");return pane;}

    private void searchPrivateMessages(){if(selectedUser==null){system("Open a private conversation first.");return;}TextInputDialog d=new TextInputDialog();d.setTitle("Search messages");d.setHeaderText("Search this account's private messages");d.setContentText("Search text:");d.showAndWait().map(String::trim).filter(q->!q.isEmpty()).ifPresent(q->{try{connection.send(MessageType.C2S_SEARCH_PRIVATE_MESSAGES,new SearchPrivateMessagesRequest(q,50));}catch(IOException e){system(e.getMessage());}});}
    private void showSearchResults(PrivateSearchResultsResponse response){ListView<String> results=new ListView<>();if(response!=null&&response.getResults()!=null)for(PrivateSearchResult r:response.getResults()){String who=r.getSenderId()==session.getUserId()?"You":r.getSenderUsername();results.getItems().add(who+": "+r.getMessage());}if(results.getItems().isEmpty())results.getItems().add("No messages found.");results.setPrefSize(620,420);Dialog<Void> dialog=new Dialog<>();dialog.setTitle("Message search");dialog.setHeaderText("Results for \""+response.getQuery()+"\"");dialog.getDialogPane().setContent(results);dialog.getDialogPane().getButtonTypes().add(ButtonType.CLOSE);dialog.showAndWait();}
    private void openUser(UserSummary u){stopTyping();selectedUser=u;selectedGroup=null;unreadUsers.remove(u.getUserId());refreshConversationLists();conversationTitle.setText(u.getUsername());clearConversation();try{connection.send(MessageType.C2S_REQUEST_PRIVATE_HISTORY,new PrivateHistoryRequest(u.getUserId(),100,0));}catch(IOException e){system(e.getMessage());}}
    private void openGroup(GroupSummary g){stopTyping();selectedGroup=g;selectedUser=null;unreadGroups.remove(g.getGroupId());refreshConversationLists();conversationTitle.setText("# "+g.getName());clearConversation();try{connection.send(MessageType.C2S_REQUEST_GROUP_HISTORY,new GroupHistoryRequest(g.getGroupId(),100,0));}catch(IOException e){system(e.getMessage());}}
    private void clearConversation(){messages.getItems().clear();renderedMessageRows.clear();setTypingVisible(false);}
    private void sendMessage(){String text=composer.getText().trim();if(text.isEmpty())return;stopTyping();try{if(selectedUser!=null)connection.send(MessageType.C2S_PRIVATE_MESSAGE,new PrivateMessageRequest(selectedUser.getUserId(),text));else if(selectedGroup!=null)connection.send(MessageType.C2S_GROUP_MESSAGE,new GroupMessageRequest(selectedGroup.getGroupId(),text));else{system("Select a conversation first.");return;}composer.clear();}catch(IOException e){system(e.getMessage());setConnectionState(false);}}
    private void handleTypingInput(String value){if(selectedUser==null||session==null||!connection.isConnected())return;if(value==null||value.isBlank()){stopTyping();return;}try{if(!typingActive){connection.send(MessageType.C2S_TYPING_START,new PrivateMessageRequest(selectedUser.getUserId(),""));typingActive=true;}if(typingStopTask!=null)typingStopTask.cancel(false);typingStopTask=typingScheduler.schedule(this::stopTyping,900,TimeUnit.MILLISECONDS);}catch(IOException e){setConnectionState(false);}}
    private void stopTyping(){if(typingStopTask!=null){typingStopTask.cancel(false);typingStopTask=null;}if(typingActive&&selectedUser!=null&&connection.isConnected())try{connection.send(MessageType.C2S_TYPING_STOP,new PrivateMessageRequest(selectedUser.getUserId(),""));}catch(IOException ignored){}typingActive=false;}
    private void createGroup(){TextInputDialog d=new TextInputDialog();d.setTitle("New group");d.setHeaderText("Create a group");d.setContentText("Group name:");d.showAndWait().map(String::trim).filter(s->!s.isEmpty()).ifPresent(name->{try{connection.send(MessageType.C2S_CREATE_GROUP,new CreateGroupRequest(name));}catch(IOException e){system(e.getMessage());}});}
    private void joinGroup(){TextInputDialog d=new TextInputDialog();d.setTitle("Join group");d.setHeaderText("Enter numeric group ID");d.setContentText("Group ID:");d.showAndWait().ifPresent(id->{try{connection.send(MessageType.C2S_JOIN_GROUP,new GroupJoinRequest(Integer.parseInt(id.trim())));}catch(NumberFormatException e){system("Group ID must be a number.");}catch(IOException e){system(e.getMessage());}});}
    private void requestData(){try{connection.send(MessageType.C2S_REQUEST_USER_LIST,null);connection.send(MessageType.C2S_REQUEST_GROUP_LIST,null);}catch(IOException e){setConnectionState(false);}}
    private void onEnvelope(Envelope envelope){Platform.runLater(()->{try{switch(envelope.getType()){case S2C_USER_LIST->users.setAll(codec.unwrap(envelope,UserListResponse.class).getUsers());case S2C_USER_ONLINE,S2C_USER_OFFLINE->requestData();case S2C_GROUP_LIST->groups.setAll(codec.unwrap(envelope,GroupListResponse.class).getGroups());case S2C_GROUP_CREATED->{GroupSummary group=codec.unwrap(envelope,GroupCreatedResponse.class).getGroup();groups.removeIf(g->g.getGroupId()==group.getGroupId());groups.add(group);openGroup(group);}case S2C_PRIVATE_HISTORY->{PrivateHistoryResponse r=codec.unwrap(envelope,PrivateHistoryResponse.class);if(selectedUser!=null&&selectedUser.getUserId()==r.getOtherUserId()){clearConversation();r.getMessages().forEach(this::privateMessage);markHistoryRead(r);}}case S2C_PRIVATE_MESSAGE->privateMessage(codec.unwrap(envelope,PrivateMessageEvent.class));case S2C_PRIVATE_SEARCH_RESULTS->showSearchResults(codec.unwrap(envelope,PrivateSearchResultsResponse.class));case S2C_MESSAGE_DELIVERED->updateMessageStatus(codec.unwrap(envelope,PrivateMessageEvent.class));case S2C_MESSAGE_READ->updateMessageRead(codec.unwrap(envelope,MessageReadRequest.class));case S2C_TYPING_START->{TypingEvent t=codec.unwrap(envelope,TypingEvent.class);if(selectedUser!=null&&t!=null&&t.getUserId()==selectedUser.getUserId())setTypingVisible(true);}case S2C_TYPING_STOP->{TypingEvent t=codec.unwrap(envelope,TypingEvent.class);if(selectedUser!=null&&t!=null&&t.getUserId()==selectedUser.getUserId())setTypingVisible(false);}case S2C_GROUP_HISTORY->{GroupHistoryResponse r=codec.unwrap(envelope,GroupHistoryResponse.class);if(selectedGroup!=null&&selectedGroup.getGroupId()==r.getGroupId()){clearConversation();r.getMessages().forEach(this::groupMessage);}}case S2C_GROUP_MESSAGE->groupMessage(codec.unwrap(envelope,GroupMessageEvent.class));case S2C_ERROR->{AuthFailedResponse error=codec.unwrap(envelope,AuthFailedResponse.class);setConnectionState(connection.isConnected());system(error==null||error.getMessage()==null?"Server rejected the request.":error.getMessage());}case S2C_NOTIFICATION->{NotificationEvent n=codec.unwrap(envelope,NotificationEvent.class);if(n!=null){String title=n.getTitle()==null?"Notification":n.getTitle();String message=n.getMessage()==null?"":n.getMessage();system(message.isBlank()?title:title+": "+message);}}default->{}}}catch(RuntimeException e){system("Received an invalid server response.");}});}
    private void markHistoryRead(PrivateHistoryResponse r){if(session==null||r.getMessages()==null)return;for(PrivateMessageEvent m:r.getMessages())if(m.getReceiverId()==session.getUserId()&&m.getMessageId()>0)sendReadReceipt(m.getMessageId());}
    private void sendReadReceipt(long id){try{connection.send(MessageType.C2S_MESSAGE_READ,new MessageReadRequest(id));}catch(IOException e){setConnectionState(false);}}
    private void privateMessage(PrivateMessageEvent m){if(m==null||session==null)return;boolean belongs=m.getSenderId()==session.getUserId()&&selectedUser!=null&&m.getReceiverId()==selectedUser.getUserId()||m.getReceiverId()==session.getUserId()&&selectedUser!=null&&m.getSenderId()==selectedUser.getUserId();if(!belongs){if(m.getReceiverId()==session.getUserId()&&m.getSenderId()!=session.getUserId())incrementUnreadUser(m.getSenderId());return;}String sender=m.getSenderId()==session.getUserId()?"You":selectedUser.getUsername();String status=m.getSenderId()==session.getUserId()?statusSuffix(m.getStatus()):"";int row=messages.getItems().size();messages.getItems().add(sender+": "+m.getMessage()+status);if(m.getSenderId()==session.getUserId()&&m.getMessageId()>0)renderedMessageRows.put(m.getMessageId(),row);messages.scrollTo(row);if(m.getReceiverId()==session.getUserId()&&m.getSenderId()!=session.getUserId()&&m.getMessageId()>0)sendReadReceipt(m.getMessageId());}
    private void incrementUnreadUser(int userId){unreadUsers.merge(userId,1,Integer::sum);refreshConversationLists();} private void incrementUnreadGroup(int groupId){unreadGroups.merge(groupId,1,Integer::sum);refreshConversationLists();}
    private void refreshConversationLists(){if(!Platform.isFxApplicationThread()){Platform.runLater(this::refreshConversationLists);return;}if(peopleView!=null)peopleView.refresh();if(groupView!=null)groupView.refresh();}
    private void updateMessageStatus(PrivateMessageEvent e){if(e==null||e.getMessageId()<=0)return;Integer row=renderedMessageRows.get(e.getMessageId());if(row==null)return;messages.getItems().set(row,stripStatus(messages.getItems().get(row))+"  ✓ delivered");}
    private void updateMessageRead(MessageReadRequest r){if(r==null)return;Integer row=renderedMessageRows.get(r.getMessageId());if(row==null)return;messages.getItems().set(row,stripStatus(messages.getItems().get(row))+"  ✓✓ read");}
    private static String stripStatus(String text){return text.replaceAll("\\s+✓{1,2} (?:delivered|read)$","");} private static String statusSuffix(String status){if("READ".equalsIgnoreCase(status))return "  ✓✓ read";if("DELIVERED".equalsIgnoreCase(status))return "  ✓ delivered";return "  ✓ sent";}
    private void groupMessage(GroupMessageEvent m){if(m==null||selectedGroup==null||session==null){if(m!=null&&session!=null&&m.getSenderId()!=session.getUserId())incrementUnreadGroup(m.getGroupId());return;}if(m.getGroupId()!=selectedGroup.getGroupId()){if(m.getSenderId()!=session.getUserId())incrementUnreadGroup(m.getGroupId());return;}String sender=m.getSenderId()==session.getUserId()?"You":m.getSenderUsername();int row=messages.getItems().size();messages.getItems().add(sender+": "+m.getMessage());messages.scrollTo(row);}
    private void setTypingVisible(boolean visible){if(typingLabel==null)return;typingLabel.setVisible(visible);typingLabel.setManaged(visible);if(visible)typingLabel.setText(selectedUser==null?"Typing…":selectedUser.getUsername()+" is typing…");}
    private void setConnectionState(boolean connected){if(!Platform.isFxApplicationThread()){Platform.runLater(()->setConnectionState(connected));return;}if(connectionStatus==null)return;connectionStatus.setText(connected?"● Connected":"● Disconnected");connectionStatus.getStyleClass().removeAll("connected","disconnected");connectionStatus.getStyleClass().add(connected?"connected":"disconnected");if(!connected)stopTyping();}
    private void system(String text){if(text!=null&&!text.isBlank())messages.getItems().add("System: "+text);} private void ensureConnected()throws IOException{if(!connection.isConnected())connection.connect(host,port);setConnectionState(true);}
    private static Label section(String text){Label l=new Label(text);l.getStyleClass().add("section-label");return l;} private static Button primary(String text){Button b=new Button(text);b.setDefaultButton(true);b.getStyleClass().add("primary");return b;}
    private static String errorText(Throwable t){Throwable c=t;while((c instanceof java.util.concurrent.CompletionException||c instanceof java.util.concurrent.ExecutionException)&&c.getCause()!=null)c=c.getCause();return c.getMessage()==null?"Request failed.":c.getMessage();}
    private static <T> void runAsync(Supplier<T> work,Consumer<T> success,Consumer<Throwable> failure){Thread.ofVirtual().start(()->{try{T value=work.get();Platform.runLater(()->success.accept(value));}catch(Throwable error){Platform.runLater(()->failure.accept(error));}});} private interface Supplier<T>{T get()throws Exception;}
    @Override public void stop(){stopTyping();typingScheduler.shutdownNow();connection.close();}
}
