name: Scorecards supply-chain security

on:
  push:
    branches: [main]
  schedule:
    - cron: '30 3 * * 1'
  workflow_dispatch:

permissions: read-all

concurrency:
  group: scorecards-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  analysis:
    name: Scorecards analysis
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      security-events: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          persist-credentials: false

      - name: Run Scorecard analysis
        uses: ossf/scorecard-action@e8e61e86ea0a152be84d03729c02a7300065c17d
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

      - name: Upload Scorecard artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: scorecard-results
          path: results.sarif
          if-no-files-found: error
          retention-days: 5

      - name: Upload Scorecard results to code scanning
        uses: github/codeql-action/upload-sarif@cdf488f595d80d6e07e03d4674febd5ab45fa938 # v4
        with:
          sarif_file: results.sarif
